### ISSUE TITLE
Improve documentation!

### ISSUE THREAD

**Issue by D-McGovern** [SFDO-Community-Sprints/MembershipSchemaAndBenefits#60] opened 2021-06-10 20:36 UTC
It would be great to get fresh eyes on current functionality and build out the documentation page of the WIki to cover expected behavior around automated dates, add help text to fields, document fringe cases, etc

**Comment by brandonmead** [comment] 2022-05-05 19:50
Updated Wiki by adding the "Getting Started" section to Membership Package Documentation. This section explains adding a membership as a Product first and what membership fields have been added to the Product object. Additionally, there is a disclaimer about why a Product type of membership was not added and how a user can add this themselves if they so desire.

Updated Product Object fields in the "Working Document" (See Wiki>Membership Package Documentation>Data Dictionary)

**Comment by kreynen** [comment] 2023-02-01 00:21
There has been a lot of documentation added since this issue was opened. We are now at the point the issue isn't a lack of documentation, but the quality and organization. Closing in favor of https://github.com/SFDO-Community-Sprints/MembershipSchemaAndBenefits/issues/82 and issues about improvements to specific parts of the documentation.

**Closed by kreynen** 2023-02-01 00:21 UTC
Labels: documentation, good first issue, up next
